"""Genera docs/strapi/seed-mensaje-uis.json con todas las cadenas de interfaz en español."""
import json
from pathlib import Path

UI = {
    "dashboard.header.title": "Parqueadero UCO",
    "dashboard.header.subtitle": "Sistema de gestión de espacios",
    "dashboard.stats.available": "Espacios disponibles",
    "dashboard.stats.occupied": "Espacios ocupados",
    "dashboard.stats.reserved": "Reservados",
    "dashboard.section.mapTitle": "Mapa del parqueadero",
    "dashboard.legend.available": "Disponible",
    "dashboard.legend.occupied": "Ocupado",
    "dashboard.legend.reserved": "Reservado",
    "dashboard.loading": "Cargando cupos…",
    "dashboard.status.available": "Libre",
    "dashboard.status.occupied": "Ocupado",
    "dashboard.status.reserved": "Reservado",
    "dashboard.release": "Liberar",
    "dashboard.releasing": "Liberando…",
    "dashboard.modal.reserveTitle": "Reservar espacio",
    "dashboard.modal.releaseTitle": "Liberar espacio",
    "dashboard.modal.reserveBody": "¿Deseas reservar el espacio {id}? Indica placa y franja horaria.",
    "dashboard.modal.releaseBody": "¿Deseas liberar el espacio {id}? (Cancela reserva u ocupación según el estado actual).",
    "dashboard.plate.label": "Placa del vehículo",
    "dashboard.plate.placeholder": "Ej: ABC12A",
    "dashboard.plate.registeredLabel": "Placa registrada:",
    "dashboard.reservedScheduleLabel": "Horario reservado:",
    "dashboard.time.startLabel": "Hora de entrada",
    "dashboard.time.endLabel": "Hora de salida",
    "dashboard.selectPlaceholder": "Seleccionar",
    "dashboard.parkingHours": "Horario del parqueadero: 7:00 a. m. – 9:40 p. m.",
    "dashboard.cancel": "Cancelar",
    "dashboard.processing": "Procesando…",
    "dashboard.reserve": "Reservar",
    "dashboard.confirm": "Confirmar",
    "dashboard.plateError.enter": "Ingresa la placa del vehículo",
    "dashboard.timeError.selectBoth": "Por favor selecciona la hora de inicio y fin",
    "dashboard.timeError.endAfterStart": "La hora de fin debe ser mayor a la hora de inicio",
    "dashboard.error.loadSpots": "No se pudieron cargar los cupos",
    "dashboard.error.reserve": "No se pudo reservar el cupo",
    "dashboard.error.release": "No se pudo liberar el cupo",
    "register.header.title": "Registrar estudiante",
    "register.header.subtitle": "Completa los datos",
    "register.section.personal": "INFORMACIÓN PERSONAL",
    "register.section.contact": "INFORMACIÓN DE CONTACTO",
    "register.section.academic": "INFORMACIÓN ACADÉMICA",
    "register.field.name": "NOMBRE",
    "register.field.lastName": "APELLIDO",
    "register.field.idType": "TIPO DE DOCUMENTO",
    "register.field.idNumber": "NÚMERO DE DOCUMENTO",
    "register.field.email": "CORREO ELECTRÓNICO",
    "register.field.mobile": "CELULAR",
    "register.field.program": "PROGRAMA ACADÉMICO",
    "register.requiredMark": "*",
    "register.placeholder.name": "Ej: Juan",
    "register.placeholder.lastName": "Ej: Pérez",
    "register.placeholder.idNumber": "Ej: 1234567890",
    "register.placeholder.email": "Ej: juan@ucordoba.edu.co",
    "register.placeholder.mobile": "Ej: 3001234567",
    "register.select.idType": "Selecciona...",
    "register.select.program": "Selecciona el programa...",
    "register.idType.cc": "Cédula de ciudadanía",
    "register.idType.ti": "Tarjeta de identidad",
    "register.idType.passport": "Pasaporte",
    "register.idType.ce": "Cédula de extranjería",
    "register.program.systems": "Ingeniería de Sistemas",
    "register.program.law": "Derecho",
    "register.program.business": "Administración de Empresas",
    "register.actions.cancel": "Cancelar",
    "register.actions.save": "Registrar estudiante",
    "register.error.postRegisterUuid": "Estudiante registrado, pero no se pudo obtener el UUID. Cierra sesión e inicia de nuevo para continuar.",
    "register.error.submitPrefix": "Error al registrar:",
    "register.error.submitWithDetail": "Error al registrar: {detail}",
    "register.validation.name": "El nombre es obligatorio",
    "register.validation.lastName": "El apellido es obligatorio",
    "register.validation.idType": "El tipo de documento es obligatorio",
    "register.validation.idNumber": "El número de documento es obligatorio",
    "register.validation.email": "El correo es obligatorio",
    "register.validation.mobile": "El celular es obligatorio",
    "register.validation.program": "El programa académico es obligatorio",
    "login.brand.sub": "SISTEMA DE GESTIÓN DE PARQUEO",
    "login.stat.online": "En línea",
    "login.stat.campus": "Campus",
    "login.stat.av247value": "24/7",
    "login.stat.av247caption": "Disponible",
    "login.stat.percentValue": "100%",
    "login.logo.alt": "Logotipo de UcoParking",
    "login.welcome": "Bienvenido",
    "login.hint.checking": "Comprobando sesión…",
    "login.hint.auth0": "Ingresa con tu cuenta institucional o personal a través de Auth0.",
    "login.btn.login": "Iniciar sesión",
    "login.btn.signup": "Crear cuenta",
    "login.btn.redirecting": "Redirigiendo…",
    "login.university": "Universidad Católica de Oriente",
    "login.error.sessionVerify": "No se pudo verificar la sesión.",
    "login.error.loginFailed": "No se pudo iniciar sesión.",
    "login.error.signupFailed": "No se pudo abrir el registro.",
    "login.error.auth0Url": "Auth0: {code}{suffix}",
    "sidebar.brand.sub": "GESTIÓN DE PARQUEO",
    "sidebar.nav.reserve": "Reserva de sitio",
    "sidebar.nav.register": "Registrar estudiante",
    "sidebar.nav.apiTests": "Pruebas API",
    "sidebar.nav.students": "Estudiantes",
    "sidebar.nav.settings": "Configuración",
    "router.title.register": "Registro de estudiante",
    "router.title.dashboard": "Reserva de sitio",
    "router.title.apiTests": "Pruebas API",
    "router.title.students": "Estudiantes",
    "router.title.settings": "Configuración",
    "router.title.login": "Iniciar sesión",
    "placeholder.subtitle": "Sección en construcción",
    "placeholder.body": "Esta sección estará disponible próximamente.",
    "app.browserTitle": "{page} · UcoParking",
    "notifications.unknown": "Error desconocido",
    "bootstrap.configErrorTitle": "Error de configuración",
    "api.sessionMissing": "No hay estudiante en sesión: inicia sesión con un correo registrado en el API o define VITE_STUDENT_UUID en .env.local (solo desarrollo).",
    "api.httpStatusFallback": "Error HTTP {status}",
    "student.createFailed": "Error al registrar el estudiante",
    "validators.plateHint": "Formato: 3 letras, 2 números y 1 letra o número (6 caracteres). Ejemplos: ABC12A o XYZ99Z.",
    "auth0.missingEnv": "Faltan VITE_AUTH0_DOMAIN o VITE_AUTH0_CLIENT_ID. Copia .env.example a .env.local o define los secretos en Infisical y ejecuta npm run dev:secrets.",
    "auth0.clientNotInitialized": "Auth0 no está inicializado: llama a initAuth0() antes de usar el cliente.",
    "header.logout": "Salir",
    "header.userStudent": "Estudiante",
    "header.userFallback": "Usuario",
    "toast.kind.error": "ERROR",
    "toast.aria.close": "Cerrar aviso {code}",
    "email.reserva.asunto": "Reserva de parqueadero confirmada – UcoParking",
    "email.reserva.cuerpoHtml": "<h2>¡Hola, {{nombreEstudiante}}!</h2><p>Tu reserva en el cupo <strong>{{cupo}}</strong> ha sido confirmada.</p><ul><li><strong>Placa:</strong> {{placa}}</li><li><strong>Franja (America/Bogotá):</strong> {{horaInicio}} – {{horaFin}}</li></ul><p>Recuerda llegar a tiempo y respetar el horario.</p><p>— Equipo UcoParking · Universidad Católica de Oriente</p>",
}

root = Path(__file__).resolve().parents[1]
rows = [{"clave": k, "valor": v} for k, v in sorted(UI.items())]
out = root / "docs" / "strapi" / "seed-mensaje-uis.json"
out.write_text(json.dumps(rows, ensure_ascii=False, indent=2), encoding="utf-8")
print("written", out, "entries", len(rows))
